spring.application.name=taskmanager

# Railway dynamic variables with local fallbacks
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:task_manager}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true


spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:Madhur@1234}

# Force the dialect to prevent the "Unable to determine Dialect" crash
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Allow Railway to assign a port dynamically
server.port=${PORT:8080}